p1805_hw1_zo2168
================

# Problem 1

``` r
data("penguins", package = "palmerpenguins")
colnames(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
distinct(penguins, species)
```

    ## # A tibble: 3 × 1
    ##   species  
    ##   <fct>    
    ## 1 Adelie   
    ## 2 Gentoo   
    ## 3 Chinstrap

``` r
distinct(penguins,island)
```

    ## # A tibble: 3 × 1
    ##   island   
    ##   <fct>    
    ## 1 Torgersen
    ## 2 Biscoe   
    ## 3 Dream

``` r
distinct(penguins, sex)
```

    ## # A tibble: 3 × 1
    ##   sex   
    ##   <fct> 
    ## 1 male  
    ## 2 female
    ## 3 <NA>

``` r
max(pull(penguins, bill_length_mm), na.rm = T)
```

    ## [1] 59.6

``` r
min(pull(penguins, bill_length_mm), na.rm = T)
```

    ## [1] 32.1

``` r
max(pull(penguins, bill_depth_mm), na.rm = T)
```

    ## [1] 21.5

``` r
min(pull(penguins, bill_depth_mm), na.rm = T)
```

    ## [1] 13.1

``` r
max(pull(penguins, flipper_length_mm), na.rm = T)
```

    ## [1] 231

``` r
min(pull(penguins, flipper_length_mm), na.rm = T)
```

    ## [1] 172

``` r
max(pull(penguins, body_mass_g), na.rm = T)
```

    ## [1] 6300

``` r
min(pull(penguins, body_mass_g), na.rm = T)
```

    ## [1] 2700

``` r
range(pull(penguins, year),na.rm = T)
```

    ## [1] 2007 2009

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins, flipper_length_mm), na.rm = T)
```

    ## [1] 200.9152

The variable names include
`species`,`island`,`bill_length_mm`,`bill_depth_mm`,`flipper_length_mm`,`body_mass_g`,
`sex`, `year`.  
Three `species` are *Adelie*, *Gentoo*, *Chinstrap*,  
Three `island` are *Torgersen*, *Biscoe*, *Dream*,  
The maximum and minimum of `bill_length_mm` are 59.6 mm and 32.1 mm
respectively  
The maximum and minimum of `bill_depth_mm` are 21.5 mm and 13.1 mm
respectively  
The maximum and minimum of `flipper_length_mm` are 231 mm and 172 mm
respectively  
The maximum and minimum of `body_mass_g` are 6300 and 2700
respectively  
`Year` ranges from 2007 to 2009  
`sex` includes male and female  
This dataset has 344 rows and 8 columns  
Mean flipper length is 200.9152

# Problem 2

I can take the mean of the sample, too! The mean is
